server:
  port: 8888

eureka-server:
  name: 127.0.0.1
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka-server.name}:${eureka-server.port}/eureka/

#
##配置文件在本地
#spring:
#  profiles:
#    active: native
#  #配置文件的目录
#  cloud:
#    config:
#      server:
#        native:
#          # 搜索src/main/resource 下的properties文件夹下的文件
#          search-locations: classpath:properties/
spring:
  cloud:
    config:
      server:
        git:
          uri: http://47.105.108.6/zcx5825585/spring-cloud-config.git
          search-paths: /
#          todo
#          username:
#          password:
      label: master

  application:
    name: config-server